### ISSUE TITLE
NullPointerException due to AsyncTask running after Activity is terminated

### ISSUE THREAD

**Issue by aboev** [aboev/photobook-client#3]
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver com.freecoders.photobook.MainActivity.getContentResolver()' on a null object reference
at com.freecoders.photobook.db.ContactsRetrieverTask.getContacts(ContactsRetrieverTask.java:104)
at com.freecoders.photobook.db.ContactsRetrieverTask.doInBackground(ContactsRetrieverTask.java:38)
at com.freecoders.photobook.db.ContactsRetrieverTask.doInBackground(ContactsRetrieverTask.java:25)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more

**Comment by aboev** [comment]
Fixed in 3e226c34cb4aa59b8dd1be2fc7df201420be5884
